### ISSUE TITLE
Credits for 1.0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-compare#13]
Complete credits for 1.0 release.   QA credits will not be finalized until after final RC test.

Should credits be shared with number-play-main.ts?

**Comment by marlitas** [comment]
@KatieWoe and @amanda-phet we are unsure if the credits here are accurate, they may just be duplicated. Can you double check with the understanding QA credits may change once we go through dev testing?

```
leadDesign: 'Amanda McGarry',
softwareDevelopment: 'Chris Klusendorf, Luisa Vargas',
team: 'Sylvia Celedón-Pattichis, Ariel Paul, Kathy Perkins, Ian Whitacre, Chris Malley (PixelZoom, Inc.), Marla Schulz, Michael Kauzmann',
qualityAssurance: 'Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
graphicArts: 'Mariah Hermsmeyer',
thanks: 'Andrea Barraugh (Math Transformations), Kristin Donley, Bertha Orona'
```

**Comment by pixelzoom** [comment]
> ... with the understanding QA credits may change once we go through dev testing?

FYI... Credits typically change throughout the QA process, including after RC tests, and right up until we publish.  And they need to be confirmed just before we publish.  So this issue most definitely blocks publication, until @KatieWoe gives the final revisions and sign-off.

**Comment by KatieWoe** [comment]
They're ok for now, but like @pixelzoom said, they may change

**Comment by amanda-phet** [comment]
Usually credits are alphabetized, so I recommend: 

```
leadDesign: 'Amanda McGarry',
softwareDevelopment: 'Chris Klusendorf, Luisa Vargas',
team: 'Sylvia Celedón-Pattichis, Michael Kauzmann, Chris Malley (PixelZoom, Inc.), Ariel Paul, Kathy Perkins, Marla Schulz, Ian Whitacre',
qualityAssurance: 'Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
graphicArts: 'Mariah Hermsmeyer',
thanks: 'Andrea Barraugh (Math Transformations), Kristin Donley, Bertha Orona'
```

**Comment by zepumph** [comment]
Cherry picked and verified in the 1.0 branch. Closing
