### ISSUE TITLE
"Hear Number Sentence" preference control has bogus description

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-compare#16]
In Number Compare, the title for this Preference control has been customized, but the description is totally incorrect:

<img width="310" alt="screenshot_2180" src="https://user-images.githubusercontent.com/3046552/213939161-5fed81fc-5184-4384-b247-d6a8672474bb.png">

**Comment by pixelzoom** [comment]
Fixed in the above commits.  @chrisklus please review.

In Number Play Preferences:
<img width="306" alt="screenshot_2182" src="https://user-images.githubusercontent.com/3046552/213939650-1b4f9399-19a0-4274-85ce-8d9931c1dc77.png">

In Number Compare Preferences:
<img width="379" alt="screenshot_2181" src="https://user-images.githubusercontent.com/3046552/213939655-b9d9adce-23c9-406e-9c90-1642c2ad115d.png">

Note that I wasn't sure exactly what the description should be in Number Compare.  Will "number sentence" make sense to the student?  It seems kind of vague to me.  But Number Play uses "total" in the control's title and description, so I went with that for Number Compare.   Feel free to change.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, these changes look good.

>Note that I wasn't sure exactly what the description should be in Number Compare. Will "number sentence" make sense to the student? It seems kind of vague to me, but it's how the control is titled.

In general, all of these preference controls seem potentially not understandable by kindergarteners since reading proficiency isn't a requirement for using the general sim. I think they will be more used by teachers and parents.

>And Number Play uses "total" in the control's title and description, so I used that same pattern for Number Compare. Feel free to change.

That looks great to me, thanks.

I think we are all set to close here.
