### ISSUE TITLE
MissingVoiceWarningButton missing

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-compare#17]
MissingVoiceWarningButton is included in Number Play but missing in Number Compare. I should factor out a type that puts these into one control and then use that in NP and NC.

**Comment by pixelzoom** [comment]
I'll take this one. Will factor out a control that includes SpeechSynthesisButton and MissingVoiceWarningButton.

**Comment by pixelzoom** [comment]
In the above commit, I factored out SpeechSynthesisControl, and used it in both NumberPlayScreenView (Ten and Twenty screens) and CompareScreenView.   Note the layout problem in the Compare screen, reported in https://github.com/phetsims/number-compare/issues/18 -- it was present before making this change.

@chrisklus please review, close if OK.

**Comment by pixelzoom** [comment]
Please ignore commit https://github.com/phetsims/beers-law-lab/commit/fe5cc1fb104b24c55ccbb516ca64f59a371c7d2b, it was incorrect associated with this issue.

**Comment by chrisklus** [comment]
Thanks @pixelzoom! Looks great. I simplified parameter typing in SpeechSynthesisButton above based on your commit in https://github.com/phetsims/number-suite-common/commit/4227ce76b284a23d0b6fd42101a3cf733359d3e1. Closing.
