### ISSUE TITLE
Insufficent space for the LocaleSwitch in the Compare screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-compare#18]
There is insufficent space for the LocaleSwitch in the Compare screen. To reproduce:

1. Run the sim with `locales=*`
2. Go to the Compare screen
3. Go to Preferences dialog, choose Simulation tab.
4. Turn on "Second Language" toggle, choose "español (España)"
5. Close the Preferences dialog.
6. Note that the LocaleSwitch is really compromised. The  "español (España)" is in tiny font, and it's kissing the accordion box to its right. Here's a screenshot:
7. 
<img width="413" alt="screenshot_2229" src="https://user-images.githubusercontent.com/3046552/215921306-be9f427d-bff6-410b-be32-b1adab4c3a63.png">

This feels like a fundamental design flaw -- there simply is not enough space for this control.  Since this compromises the UX, I think it needs to be resolved for publication.

**Comment by pixelzoom** [comment]
Here's another example when running with `locale=es_MX&locales=*`.  I doubt that our Mexican users will be happy with this UX.

<img width="425" alt="screenshot_2230" src="https://user-images.githubusercontent.com/3046552/215921851-7d84ea04-f818-4875-a129-8db2f126d9ba.png">

**Comment by pixelzoom** [comment]
The most expedient fix woud be to move the toggle switch down, and increase the maxWidth for its labels.  See first screenshot below.

I realize that you probably placed it in proximilty to the SpeechSynthesisButton.  But the toggle also lacks proximity to that button in Number Play, so you'd be consistent :) See second screenshot below.

<img width="1085" alt="screenshot_2234" src="https://user-images.githubusercontent.com/3046552/216080401-acf992eb-4e8d-4067-b647-9668d0dba67f.png">

<img width="1087" alt="screenshot_2235" src="https://user-images.githubusercontent.com/3046552/216080971-fe36a633-c64d-435c-ae0d-2da47c67b0b4.png">

**Comment by amanda-phet** [comment]
The location you proposed looks great to me! It's in line with the sentence that it's translating, so I think it works.

**Comment by pixelzoom** [comment]
Ugh, we still have a space problem here. With `stringTest=long`, you can see that the "sentence" grows to overlap the toggle.  Screenshot below.  I'm hesitant to change the maxWidth for the sentence, because I suspect that it was purposely set to this width, and the text already seems a bit too small to me (even in English).

@amanda-phet thoughts? 

<img width="1089" alt="screenshot_2238" src="https://user-images.githubusercontent.com/3046552/216144673-deda9243-a944-4b05-8489-e24245926924.png">

**Comment by pixelzoom** [comment]
Brainstorming... I was going to suggest using radio buttons instead of a toggle switch for this sim.  But I don't like the fact that it would be a different control than in the Number Play sim. And there would still have a space problem, see mockup below.

<img width="797" alt="screenshot_2240" src="https://user-images.githubusercontent.com/3046552/216145831-0bccfe8d-1785-422a-87dd-ff822241ec04.png">

**Comment by amanda-phet** [comment]
I don't know what to do! 

Here is a wild idea. Instead of a max width for the sentence, can we have a max width while center-justified, and if it reaches that max width, it will change to become left-justified? So in the case of a super long string, the string would actually not look centered anymore, and would use that space to the right of where the long string currently is? 

![image](https://user-images.githubusercontent.com/7852916/216712355-d21235a6-ae95-4a64-a3ae-d3445454d10e.png)

**Comment by amanda-phet** [comment]
Discussed this 2/6/23 and decided to try radio buttons. @pixelzoom will take it from here.

**Comment by pixelzoom** [comment]
More notes from 2/6/23 design meeting with @amanda-phet @chrisklus @catherinecarter @marlitas @pixelzoom 

We identified this configuration as a particularly long sentence,`?locale=st&secondLocale=en_GB`:

<img width="982" alt="screenshot_2277" src="https://user-images.githubusercontent.com/3046552/217055939-b76774f4-e787-48c0-9ab7-858a8aeeb867.png">

We considered shifting the sentence to the right (@amanda-phet's suggesting in https://github.com/phetsims/number-compare/issues/18#issuecomment-1416412393) and decided that this would not be a good UX, and would be a complicated layout.

We considered moving buttons around, so that we could move the toggle more toward the left edge of the layoutBounds. But we didn't like that layout.  

@amanda-phet suggested moving the toggle to the right side of the ScreenView. But there's really no space there, and the toggle would no longer be in proximity to the speech button.

@amanda-phet asked if we really needed long locale names like "English (United Kingdom)".   Those are standard names, and not something that we can consider changing.

We finally decided that using radio buttons would be the lesser of all evils.  We don't like the inconsistency of UI between the 2 sims, and there's an additional (duplicate) development cost.  But we can't figure out how to make the same control work in both sims.  @pixelzoom will implement radio buttons.

**Comment by pixelzoom** [comment]
@chrisklus @amanda-phet please review. There are 3 significant changes in the above commits.

(1) Locale radio buttons are now used in Number Compare.  The implementation is LocaleRadioButtonGroup. Here are some screenshots:

<img width="1107" alt="screenshot_2278" src="https://user-images.githubusercontent.com/3046552/217057078-5c7ec2bd-2d7a-401b-96b1-2fc5e4b4b5ed.png">
<img width="1105" alt="screenshot_2279" src="https://user-images.githubusercontent.com/3046552/217057110-0a8f83fa-c5c7-4953-b4c0-eedc82ae74d6.png">

<img width="1102" alt="screenshot_2280" src="https://user-images.githubusercontent.com/3046552/217057473-ba9d2442-0ec0-4fbe-a068-0c91941ba141.png">

(2) LocaleSwitch was changed to pass a DerivedProperty to Text, so that it matches the implementation of LocaleRadioButtonGroup.  This is the modern approach to supporting dynamic strings. @chrisklus FYI.

(3) Changed locale switch to be left-justified in Number Play. (The toggle switch was previously centered below the accordion box.)  I reviewed this with @chrisklus, and we agreed that it looks better and improves proximity to the speech buttons. Screenshots:

<img width="436" alt="screenshot_2275" src="https://user-images.githubusercontent.com/3046552/217056882-bed2581d-c698-43ae-ba20-2d07752eaf9f.png">
<img width="432" alt="screenshot_2276" src="https://user-images.githubusercontent.com/3046552/217056897-c0080c28-9f9a-4e68-a249-8fe9b0729264.png">

**Comment by amanda-phet** [comment]
(1) There is a bug where the radio buttons show up all the time, regardless of the preference being on. 

(3) This looks fine to me. I like that there is more room for either locale to fit.

**Comment by chrisklus** [comment]
For (3), maybe this is complex, but it would be cool if the whole control had a max width and the labels knew how to scale equally if needed. Then in the screenshot in https://github.com/phetsims/number-compare/issues/18#issuecomment-1419575077, "English (United Kingdom)" would not need to be scaled as it is right now.

**Comment by pixelzoom** [comment]
> (1) There is a bug where the radio buttons show up all the time, regardless of the preference being on.

Fixed in https://github.com/phetsims/number-compare/commit/89e730e9011d0c924b369e667300e8c77e7db887.

> For (3), maybe this is complex, but it would be cool if the whole control had a max width and the labels knew how to scale equally if needed.  ...

Done in https://github.com/phetsims/number-suite-common/commit/04b27b147e950ff6ab88aac4cc926b1423dcfea7.  See LocaleSwitch.ts line 59-73.

**Comment by chrisklus** [comment]
Awesome @pixelzoom, thanks! @marlitas and I reviewed all of the commits and tested the behavior and we like these changes. With @amanda-phet's review complete in https://github.com/phetsims/number-compare/issues/18#issuecomment-1419599763, I think we are all set to close here.

**Comment by pixelzoom** [comment]
Reopening.  I'm suddenly seeing bad maxWidth for the LocaleSwitch labels in master, see below. Did something get reverted?

<img width="337" alt="screenshot_2287" src="https://user-images.githubusercontent.com/3046552/217327041-c4fc89f5-9f50-4c3d-9a90-9cfe4a55ce55.png">

**Comment by pixelzoom** [comment]
I moved the problem reported in https://github.com/phetsims/number-compare/issues/18#issuecomment-1421212885 to https://github.com/phetsims/number-play/issues/210.  So re-closing.
