### ISSUE TITLE
Remove 'Sounds' from preferences

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-compare#19]
![image](https://user-images.githubusercontent.com/7852916/221974800-65412941-c668-49b7-80c1-48034719b425.png)

Number Compare doesn't have any sounds (Number Play has game sounds). This part of the preferences dialog is unnecessary.

**Comment by chrisklus** [comment]
Done in the above commit. @amanda-phet should we just do this in Number Play too since we couldn't get the toggle to show for Sounds there? It's just so pointless to have without a toggle.

**Comment by amanda-phet** [comment]
@chrisklus and I discussed and decided to remove this text in Number Compare (since there are no sounds) and leave it in Number Play. Both options look pretty terrible (and are even a bit confusing), but this option at least make some sense.
