### ISSUE TITLE
Shouldn't there be a limit to the number of 10 cards that can be used?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-compare#25]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/917, on the lab screen, there doesn't seem to be a limit to the number of 10 cards I can put in the play area. Shouldn't there be one?

**Visuals**
<img width="1204" alt="Screenshot 2023-03-15 at 2 55 34 PM" src="https://user-images.githubusercontent.com/87318828/225414642-d5420ca5-2464-49e5-8d27-7f72b194f71b.png">

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi, nice catch! @amanda-phet could you please comment how many ten frames we should allow? Based on the space available above, I'm thinking 10-12 maybe? After commenting, please reassign to @marlitas and @pixelzoom to implement at their convenience, whoever's up for it.

**Comment by marlitas** [comment]
Oooh mine!

**Comment by amanda-phet** [comment]
I agree, 10-12 seems the most reasonable for dev bounds (and I can't imagine a good pedagogical use beyond 10). Let's say 10.

**Comment by marlitas** [comment]
Addressed in the above commits. I started by just eliminating pickability when we reached 10 Ten Frames. However this behavior seemed a bit confusing and remembered some other use cases where the draggable icon no longer appeared as though to indicate the stack ran out.  I created a commit for that option as well. 

Below are two videos showing both options. If the first option is preferred it would be very easy to revert the second commit where we toggle the icon's visibility. 

Option 1: Limit pickability

https://user-images.githubusercontent.com/42476338/226421227-92146e44-79a7-4a1c-933e-f173dc80ea08.mov



Option 2: Limit visiblity

https://user-images.githubusercontent.com/42476338/226421056-8f21eef2-4cab-4848-b468-16525e7330db.mov


@amanda-phet & @chrisklus let me know your preference.

**Comment by chrisklus** [comment]
@marlitas and I paired on this. We decided to keep the visibility implementation because the rest of the items on this screen follow the same pattern. We also refactored `TenFrameNode.getTenFramePath` to take PathOptions so we could simplify the implementation by passing in a `visibleProperty` option that is a DerivedProperty. We think this is working as expected.

@Nancy-Salpepi can you please confirm on phettest? Feel free to close if looking good.

**Comment by Nancy-Salpepi** [comment]
Looks good! There are now 10 Ten Frames. The toolbox looks empty when all ten are in the play area and the icon reappears when one is returned. 

Closing!
