### ISSUE TITLE
Compare statement should not be read aloud when switching voices in Preferences

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-compare#26]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/917, on the Compare Screen with "Hear Number Sentence" on, I sometimes hear the "Compare" statement" after the "1,2,3" statement when switching locales. I wasn't sure if I should be hearing it at all or if I should always hear it. 
Here is what I have observed so far on the Compare Screen with "Hear Number Sentence" on :

Case 1: 
1. Go to the Localization tab and select a locale with an available voice
2. Click on the Voice -- you hear "1,2,3" only

Case 2:
1. Go to the Simulation tab and turn on Second Language
2. Choose a locale with an available voice
3. Click on the Voice -- you hear "1,2,3" in that Voice, followed by the Compare Statement in the Primary Voice

Case 3: 
1. After completing the steps in Case 2, select the  radio button for the second locale on the Compare Screen
2. Go to the Simulation tab and choose a different second language
3. Click on a Voice for that language -- you hear "1,2,3" only

Case 4:
1. After completing the steps in Case 3, return to the Localization Tab
2. Select a different locale with an available voice
3. Click on that voice -- you hear "1,2,3" in that Voice, followed by the Compare Statement in the Secondary Voice

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.6/phet/number-compare_all_phet.html
Version: 1.0.0-dev.6 2023-03-15 01:30:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1203x654
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Nice work @Nancy-Salpepi! This relates to work done for https://github.com/phetsims/number-suite-common/issues/55. Leaving self assigned to investigate the incorrect cases enumerated above.

**Comment by Nancy-Salpepi** [comment]
While using the Chromebook, I hear the compare statement using the steps in Case 1 from my original https://github.com/phetsims/number-compare/issues/26#issue-1626251517.
This happens with the "eSpeak" voices listed --ex. eSpeak Polish, eSpeak Italian--but not with ChromeOS voices.

**Comment by chrisklus** [comment]
@zepumph and I investigated this today and were able to find a fix! I had a buggy line that was trying to cancel speech for the incorrect cases above but it was not doing anything. Once fixed, 2 and 4 are working correctly on our side.

@Nancy-Salpepi could you please test on master? Please note that number-suite-common will need to be pulled on phettest. Apologies if I forgot to mention that in other issues that may need that to be pulled too.

If https://github.com/phetsims/number-compare/issues/26#issuecomment-1474294665 is still not fixed, could you please open a separate issue?

Feel free to close if 2 and 4 are fixed (not on a Chromebook).

**Comment by Nancy-Salpepi** [comment]
This looks good with the mac and the problem seems to be solved for the Chromebook as well!

Closing 🎉
