### ISSUE TITLE
Window size changing causes bad lab layout

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-compare#28]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/917
On the lab screen, changing the window size of the sim causes any items in boxes to be shifted, sometime drastically.
**Steps to reproduce**
1. Go to the lab screen
2. Pull out an organization box and put it at the left side of the screen
3. Fill the box with items
4. Change the window size

**Visuals**
![funkyposition](https://user-images.githubusercontent.com/41024075/225459883-b486cbbb-cae6-449b-a4f5-26a8b0717fc6.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.6/phet/number-compare_all_phet.html
Version: 1.0.0-dev.6 2023-03-15 01:30:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Nice catch @KatieWoe! The counting objects were correctly being moved when the ten frame gets dragged, but not when the ten frame's model position was being constrained. I pushed a fix above. Could you please test on master? Feel free to close if fixed. Thanks!

**Comment by KatieWoe** [comment]
Looks good
