### ISSUE TITLE
On Chromebook, it sometimes takes two actions before a statement is heard

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-compare#32]
**Test device**
Chromebook

**Operating System**
ChromeOS 110.0.5481.181

**Problem description**
For https://github.com/phetsims/qa/issues/917, with 'Hear Number Sentence' on, after selecting a locale that has only eSpeak voices, it usually takes 2 actions before I hear anything. 

**Steps to reproduce**
Here is one example: 
1. In the Audio Tab, turn on 'Hear Number Sentence' --compare sentence is heard in English
2. In the localization tab, select a locale that has eSpeak voices (ex. italiano on my device). DO NOT press the voice. 
3. Exit the dialog
4. Place an item in the left play area --nothing is heard
5. Place a second item in the left play area --compare statement is heard

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.6/phet/number-compare_all_phet.html
Version: 1.0.0-dev.6 2023-03-15 01:30:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1203x654
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
I asked @jessegreenberg to kindly do a bit of reproducing because he has a chromebook. He'll report back to see if pairing is the next step.

**Comment by jessegreenberg** [comment]
I am able to reproduce this pretty consistently. One way for me to reproduce is to switch between English and Bengali (eSpeak Bengali) and then just press the yellow speaker button. It happens ever time I switch, even without reload.

**Comment by jessegreenberg** [comment]
I think this is an extension of https://github.com/phetsims/gravity-force-lab-basics/issues/303 (Chromebook puts speech to sleep if not used and then takes a while to re-initialize again). I have the same problem if I do the following:

- Choose an eSpeak voice in Preferences.
- Press the yellow "Speaker" button to hear the voice.
- Let the sim sit untouched for ~30 seconds.
- Press the yellow "Speaker" button again. You won't hear anything the first time, but will hear it the second time.

**Comment by jessegreenberg** [comment]
After ~20 minutes of tinkering the bug is no longer reproducible on my Chromebook.

**Comment by chrisklus** [comment]
Thank you so much for this @jessegreenberg! I was initially wondering if this was related to switching from two announcers to one etc, but it looks like that change was finished just before dev.6 was created. There have been a number of changes related to speech synthesis since then, see https://github.com/phetsims/number-suite-common/issues/56 and the many issues tagged in that issue, so @zepumph and I are not sure what the fix was.

We recommend to mark this is as ready for review and have it verified in the next dev version. @Nancy-Salpepi could you please wait for now but confirm this in the next Number Play/Number Compare dev test? I'll be sure to link it in issues to verify, thanks! Feel free to close if still looking good at that point. And thank you again @jessegreenberg!

**Comment by Nancy-Salpepi** [comment]
This looks good in Number Play 1.1.0-dev10. @chrisklus shall we keep this open until confirmed in a Number Compare dev/rc as well?

**Comment by zepumph** [comment]
This version was published today, can you just use that one? Feel free to close if all is well

https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.7/phet/number-compare_all_phet.html

**Comment by Nancy-Salpepi** [comment]
Sounds good in Number Compare as well. 
Closing!
