### ISSUE TITLE
French Voice "Thomas" incorrectly reads some numbers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-compare#38]
**Test device**
MacBook Air m1 chip and iPad 9th generation

**Operating System**
13.3.1 

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/934, the French voice "Thomas" only says the first part ("dix") for numbers 17 (dix-sept), 18 (dix-huit), and 19 (dix-neuf). I also see this in Number Play. Not sure if anything can be done. 

I do not have this voice on mac + chrome or Win10 + chrome/FF. 

**Visuals**

https://user-images.githubusercontent.com/87318828/232114081-e6276fd2-3b90-4906-9f15-130d0774586f.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-rc.1/phet/number-compare_all_phet.html
Version: 1.0.0-rc.1 2023-04-13 21:26:42 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15
Language: en-US
Window: 1188x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by veillette** [comment]
For some context, on windows 10, I have all these french voices on chrome. ![image](https://user-images.githubusercontent.com/7633344/232120436-dbd840b3-1646-45c1-8f59-7ff9f35fe2c1.png)
None of them read incorrectly.

**Comment by zepumph** [comment]
No Thomas for me on windows 11 either. Over to @chrisklus for testing.

![image](https://user-images.githubusercontent.com/6856943/232133944-1472146f-264a-4e76-a41d-36b823248ed9.png)

**Comment by chrisklus** [comment]
Sorry, thought my comment posted earlier. Thomas is working fine for me for these cases in Number Play and Compare, MacOS 12.6

**Comment by chrisklus** [comment]
@zepumph and I feel good about closing this as a wont fix. @Nancy-Salpepi and I have had a few discrepancies in voice behavior, weird! Thanks for the issue.
