### ISSUE TITLE
Polish the triangle and circle

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-compare#7]
![image](https://user-images.githubusercontent.com/7852916/163831629-04d5a7d4-6c41-4be7-979d-935062fcfb66.png)

The slight overlap make the circle have a funny shape, so we should probably do something here like make the circle radius slightly smaller or move the triangles to the sides slightly. 

@chrisklus is going to layer the circle on top of the triangle, for now, so we don't see the pointy part overlapping.

**Comment by chrisklus** [comment]
I discovered that I created this overlap intentionally, likely to avoid too much of the tick marks from peeking through behind the tip of the triangle:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5618316/205754257-422e0abd-264f-4e1b-a08d-9b403c67d84a.png">

So I proceeded with layering the circle on top of the triangles and actually moving the triangles another half a pixel closer to the circles to cover the thicker tick marks behind the triangle:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/5618316/205754832-639fc3ef-db68-40a7-9b9e-6dce5630d698.png">

I think this is looking good and ready to close. @amanda-phet feel free to reopen if you disagree.
